<?php
declare (strict_types = 1);
// +----------------------------------------------------------------------
// | swiftAdmin 极速开发框架 [基于WebMan开发]
// +----------------------------------------------------------------------
// | Copyright (c) 2020-2030 http://www.swiftadmin.net
// +----------------------------------------------------------------------
// | swiftAdmin.net High Speed Development Framework
// +----------------------------------------------------------------------
// | Author: meystack <coolsec@foxmail.com> Apache 2.0 License
// +----------------------------------------------------------------------
namespace app\admin\controller\developer;

use app\AdminController;
use Webman\Http\Request;

/**
 * 开发示例
 * <!--Developer-->
 * Class Example
 * @package app\admin\controller\developer
 */
class Example extends AdminController
{
    /**
     * 首页
     * @return \support\Response
     */
    public function index():\support\Response
    {
        return parent::index(); // TODO: Change the autogenerated stub
    }

    /**
     * echarts图标
     * @return \support\Response
     */
    public function echarts() : \support\Response
    {
        return view('/developer/example/echarts');
    }

    /**
     * echarts图标
     * @return \support\Response
     */
    public function table(): \support\Response
    {
        return view('/developer/example/table');
    }

    /**
     * echarts图标
     * @return \support\Response
     */
    public function card(): \support\Response
    {
        return view('/developer/example/card');
    }

    /**
     * echarts图标
     * @return \support\Response
     */
    public function component(): \support\Response
    {
        return view('/developer/example/component');
    }

    /**
     * echarts图标
     * @return \support\Response
     */
    public function editor(): \support\Response
    {
        return view('/developer/example/editor');
    }

    /**
     * 常规辅助元素
     * @return \support\Response
     */
    public function auxiliar(): \support\Response
    {
        return view('/developer/example/auxiliar');
    }

}
